wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: huggingface
    huggingface_version: 2.8.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      3:
      - 2
      4: 3.7.3
      5: 0.10.31
      6: 2.8.0
      8:
      - 5
batch_size:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
log_frequency:
  desc: null
  value: 100
loss:
  desc: null
  value: <deepchem.models.losses.L2Loss object at 0x7f35ac4b2550>
model_dir:
  desc: null
  value: null
optimizer:
  desc: null
  value: null
output_types:
  desc: null
  value: null
tensorboard:
  desc: null
  value: false
